# Generated by Django 2.2.2 on 2019-06-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('original', models.ImageField(default='/tmp/none.jpg', upload_to='uploads')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
