# Generated by Django 2.2.2 on 2019-06-08 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_auto_20190608_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='original_image',
            new_name='image',
        ),
    ]
